/**
 * Metadados dos bancos — fonte única usada pelo gerador de componentes e da doc.
 * slug = nome do arquivo em icons/<slug>.svg
 * compe = código de compensação Bacen (string com zeros à esquerda) ou null
 * color = override da cor de fundo quando a detecção automática erra
 */
export const BANKS = [
  { slug: "abcbrasil", component: "ABCBrasil", name: "Banco ABC Brasil", compe: "246" },
  { slug: "agibank", component: "Agibank", name: "Agibank", compe: "121" },
  { slug: "arbi", component: "Arbi", name: "Banco Arbi", compe: "213" },
  { slug: "bancodaamazonia", component: "BancoDaAmazonia", name: "Banco da Amazônia", compe: "003" },
  { slug: "bancodobrasil", component: "BancoDoBrasil", name: "Banco do Brasil", compe: "001" },
  { slug: "bancodonordeste", component: "BancoDoNordeste", name: "Banco do Nordeste", compe: "004" },
  { slug: "banese", component: "Banese", name: "Banese", compe: "047" },
  { slug: "banestes", component: "Banestes", name: "Banestes", compe: "021" },
  { slug: "banrisul", component: "Banrisul", name: "Banrisul", compe: "041" },
  { slug: "bmg", component: "BMG", name: "Banco BMG", compe: "318", color: "#f26321" },
  { slug: "bnpparibas", component: "BNPParibas", name: "Banco BNP Paribas Brasil", compe: "752" },
  { slug: "bradesco", component: "Bradesco", name: "Bradesco", compe: "237" },
  { slug: "brb", component: "BRB", name: "BRB — Banco de Brasília", compe: "070" },
  { slug: "bs2", component: "BS2", name: "Banco BS2", compe: "218" },
  { slug: "btgpactual", component: "BTGPactual", name: "BTG Pactual", compe: "208" },
  { slug: "bv", component: "BV", name: "Banco BV", compe: "655" },
  { slug: "c6bank", component: "C6Bank", name: "C6 Bank", compe: "336", color: "#000000" },
  { slug: "caixa", component: "Caixa", name: "Caixa Econômica Federal", compe: "104" },
  { slug: "citibank", component: "Citibank", name: "Citibank", compe: "745" },
  { slug: "cora", component: "Cora", name: "Cora", compe: "403" },
  { slug: "cresol", component: "Cresol", name: "Cresol", compe: "133" },
  { slug: "daycoval", component: "Daycoval", name: "Banco Daycoval", compe: "707" },
  { slug: "deutsche", component: "DeutscheBank", name: "Deutsche Bank Brasil", compe: "487" },
  { slug: "digio", component: "Digio", name: "Digio", compe: "335" },
  { slug: "efibank", component: "EfiBank", name: "Efí Bank", compe: "364" },
  { slug: "fibra", component: "Fibra", name: "Banco Fibra", compe: "224" },
  { slug: "honda", component: "BancoHonda", name: "Banco Honda", compe: null },
  { slug: "inbursa", component: "Inbursa", name: "Banco Inbursa", compe: "012" },
  { slug: "industrialdobrasil", component: "IndustrialDoBrasil", name: "Banco Industrial do Brasil", compe: "604" },
  { slug: "inter", component: "Inter", name: "Banco Inter", compe: "077" },
  { slug: "itau", component: "Itau", name: "Itaú Unibanco", compe: "341" },
  { slug: "letsbank", component: "LetsBank", name: "LetsBank", compe: "630" },
  { slug: "mercadopago", component: "MercadoPago", name: "Mercado Pago", compe: "323" },
  { slug: "mercantil", component: "Mercantil", name: "Banco Mercantil", compe: "389" },
  { slug: "mizuho", component: "Mizuho", name: "Banco Mizuho do Brasil", compe: "370" },
  { slug: "morganstanley", component: "MorganStanley", name: "Banco Morgan Stanley", compe: "066" },
  { slug: "mufg", component: "MUFG", name: "Banco MUFG Brasil", compe: "456" },
  { slug: "neon", component: "Neon", name: "Neon", compe: "735" },
  { slug: "nubank", component: "Nubank", name: "Nubank", compe: "260" },
  { slug: "omni", component: "Omni", name: "Omni Banco", compe: "613" },
  { slug: "original", component: "Original", name: "Banco Original", compe: "212" },
  { slug: "pagbank", component: "PagBank", name: "PagBank", compe: "290" },
  { slug: "pan", component: "Pan", name: "Banco Pan", compe: "623" },
  { slug: "paulista", component: "Paulista", name: "Banco Paulista", compe: "611" },
  { slug: "picpay", component: "PicPay", name: "PicPay", compe: "380" },
  { slug: "pine", component: "Pine", name: "Banco Pine", compe: "643" },
  { slug: "rendimento", component: "Rendimento", name: "Banco Rendimento", compe: "633" },
  { slug: "revolut", component: "Revolut", name: "Revolut", compe: null },
  { slug: "safra", component: "Safra", name: "Banco Safra", compe: "422" },
  { slug: "santander", component: "Santander", name: "Santander", compe: "033" },
  { slug: "sicoob", component: "Sicoob", name: "Sicoob", compe: "756" },
  { slug: "sicredi", component: "Sicredi", name: "Sicredi", compe: "748" },
  { slug: "socgen", component: "SocieteGenerale", name: "Banco Société Générale Brasil", compe: "366" },
  { slug: "sofisa", component: "Sofisa", name: "Banco Sofisa", compe: "637" },
  { slug: "starkbank", component: "StarkBank", name: "Stark Bank", compe: null },
  { slug: "stellantis", component: "BancoStellantis", name: "Banco Stellantis", compe: null },
  { slug: "stone", component: "Stone", name: "Stone", compe: "197" },
  { slug: "sumitomo", component: "SumitomoMitsui", name: "Banco Sumitomo Mitsui Brasileiro", compe: "464" },
  { slug: "topazio", component: "Topazio", name: "Banco Topázio", compe: "082" },
  { slug: "toyota", component: "BancoToyota", name: "Banco Toyota", compe: "387" },
  { slug: "unicred", component: "Unicred", name: "Unicred", compe: "136" },
  { slug: "volkswagen", component: "BancoVolkswagen", name: "Banco Volkswagen", compe: "393" },
  { slug: "willbank", component: "WillBank", name: "Will Bank", compe: null },
  { slug: "xp", component: "XP", name: "XP", compe: "348" },
  { slug: "zrobank", component: "ZroBank", name: "Zro Bank", compe: null },
];
