/**
 * Metadados dos bancos — fonte única usada pelo gerador de componentes e da doc.
 * slug = nome do arquivo em icons/<slug>.svg
 * compe = código de compensação Bacen (string com zeros à esquerda) ou null
 * color = override da cor de fundo quando a detecção automática erra
 */
export const BANKS = [
  { slug: "abcbrasil", component: "ABCBrasil", name: "Banco ABC Brasil", compe: "246" },
  { slug: "agibank", component: "Agibank", name: "Agibank", compe: "121" },
  { slug: "ailos", component: "Ailos", name: "Ailos", compe: "085" },
  { slug: "almah", component: "Almah", name: "Almah Conta", compe: null },
  { slug: "arbi", component: "Arbi", name: "Banco Arbi", compe: "213" },
  { slug: "artta", component: "Artta", name: "ARTTA", compe: null },
  { slug: "asaas", component: "Asaas", name: "Asaas", compe: "461" },
  { slug: "avenue", component: "Avenue", name: "Avenue", compe: null },
  { slug: "bancodaamazonia", component: "BancoDaAmazonia", name: "Banco da Amazônia", compe: "003" },
  { slug: "bancodobrasil", component: "BancoDoBrasil", name: "Banco do Brasil", compe: "001" },
  { slug: "bancodonordeste", component: "BancoDoNordeste", name: "Banco do Nordeste", compe: "004" },
  { slug: "banese", component: "Banese", name: "Banese", compe: "047" },
  { slug: "banestes", component: "Banestes", name: "Banestes", compe: "021" },
  { slug: "bankly", component: "Bankly", name: "Bankly", compe: "332" },
  { slug: "bankofamerica", component: "BankOfAmerica", name: "Bank of America Merrill Lynch", compe: "755" },
  { slug: "banpara", component: "Banpara", name: "Banpará", compe: "037" },
  { slug: "banrisul", component: "Banrisul", name: "Banrisul", compe: "041" },
  { slug: "beesbank", component: "BeesBank", name: "BEES Bank", compe: null },
  { slug: "bkbank", component: "BKBank", name: "BK Bank", compe: null },
  { slug: "bmg", component: "BMG", name: "Banco BMG", compe: "318", color: "#f26321" },
  { slug: "bmp", component: "BMP", name: "BMP Money Plus", compe: "274" },
  { slug: "bnpparibas", component: "BNPParibas", name: "Banco BNP Paribas Brasil", compe: "752" },
  { slug: "bradesco", component: "Bradesco", name: "Bradesco", compe: "237" },
  { slug: "brb", component: "BRB", name: "BRB — Banco de Brasília", compe: "070" },
  { slug: "bs2", component: "BS2", name: "Banco BS2", compe: "218" },
  { slug: "btgpactual", component: "BTGPactual", name: "BTG Pactual", compe: "208" },
  { slug: "bv", component: "BV", name: "Banco BV", compe: "655" },
  { slug: "c6bank", component: "C6Bank", name: "C6 Bank", compe: "336", color: "#000000" },
  { slug: "caixa", component: "Caixa", name: "Caixa Econômica Federal", compe: "104" },
  { slug: "capitual", component: "Capitual", name: "Capitual", compe: null },
  { slug: "celcoin", component: "Celcoin", name: "Celcoin", compe: "509" },
  { slug: "citibank", component: "Citibank", name: "Citibank", compe: "745" },
  { slug: "cloudwalk", component: "CloudWalk", name: "CloudWalk", compe: "542" },
  { slug: "contasimples", component: "ContaSimples", name: "Conta Simples", compe: null },
  { slug: "contbank", component: "Contbank", name: "Contbank", compe: null },
  { slug: "cora", component: "Cora", name: "Cora", compe: "403" },
  { slug: "credisis", component: "CrediSIS", name: "CrediSIS", compe: "097" },
  { slug: "creditas", component: "Creditas", name: "Creditas", compe: "342" },
  { slug: "cresol", component: "Cresol", name: "Cresol", compe: "133" },
  { slug: "daycoval", component: "Daycoval", name: "Banco Daycoval", compe: "707" },
  { slug: "deutsche", component: "DeutscheBank", name: "Deutsche Bank Brasil", compe: "487" },
  { slug: "digimais", component: "Digimais", name: "Banco Digimais", compe: "654" },
  { slug: "digio", component: "Digio", name: "Digio", compe: "335" },
  { slug: "dock", component: "Dock", name: "Dock", compe: null },
  { slug: "efibank", component: "EfiBank", name: "Efí Bank", compe: "364" },
  { slug: "fibra", component: "Fibra", name: "Banco Fibra", compe: "224" },
  { slug: "grafeno", component: "Grafeno", name: "Grafeno", compe: null },
  { slug: "honda", component: "BancoHonda", name: "Banco Honda", compe: null },
  { slug: "ifoodpago", component: "IfoodPago", name: "iFood Pago", compe: null },
  { slug: "inbursa", component: "Inbursa", name: "Banco Inbursa", compe: "012" },
  { slug: "industrialdobrasil", component: "IndustrialDoBrasil", name: "Banco Industrial do Brasil", compe: "604" },
  { slug: "infinitepay", component: "InfinitePay", name: "InfinitePay", compe: null },
  { slug: "inter", component: "Inter", name: "Banco Inter", compe: "077" },
  { slug: "itau", component: "Itau", name: "Itaú Unibanco", compe: "341" },
  { slug: "iugu", component: "Iugu", name: "iugu", compe: "401" },
  { slug: "klavi", component: "Klavi", name: "Klavi", compe: null },
  { slug: "letsbank", component: "LetsBank", name: "LetsBank", compe: "630" },
  { slug: "linker", component: "Linker", name: "Linker", compe: null },
  { slug: "magalupay", component: "MagaluPay", name: "MagaluPay", compe: "396" },
  { slug: "mercadopago", component: "MercadoPago", name: "Mercado Pago", compe: "323" },
  { slug: "mercantil", component: "Mercantil", name: "Banco Mercantil", compe: "389" },
  { slug: "mizuho", component: "Mizuho", name: "Banco Mizuho do Brasil", compe: "370" },
  { slug: "modobank", component: "Modobank", name: "Modobank", compe: null },
  { slug: "morganstanley", component: "MorganStanley", name: "Banco Morgan Stanley", compe: "066" },
  { slug: "mufg", component: "MUFG", name: "Banco MUFG Brasil", compe: "456" },
  { slug: "multiplobank", component: "MultiploBank", name: "Múltiplo Bank", compe: null },
  { slug: "neon", component: "Neon", name: "Neon", compe: "735" },
  { slug: "next", component: "Next", name: "Next", compe: null },
  { slug: "ngcash", component: "NGCash", name: "NG.CASH", compe: null },
  { slug: "nomad", component: "Nomad", name: "Nomad", compe: null },
  { slug: "nubank", component: "Nubank", name: "Nubank", compe: "260" },
  { slug: "omiecash", component: "OmieCash", name: "Omie.Cash", compe: null },
  { slug: "omni", component: "Omni", name: "Omni Banco", compe: "613" },
  { slug: "original", component: "Original", name: "Banco Original", compe: "212" },
  { slug: "orionpay", component: "OrionPay", name: "OrionPay", compe: null },
  { slug: "ourinvest", component: "Ourinvest", name: "Banco Ourinvest", compe: "712" },
  { slug: "pagarme", component: "PagarMe", name: "Pagar.me", compe: null },
  { slug: "pagbank", component: "PagBank", name: "PagBank", compe: "290" },
  { slug: "pan", component: "Pan", name: "Banco Pan", compe: "623" },
  { slug: "paulista", component: "Paulista", name: "Banco Paulista", compe: "611" },
  { slug: "paycash", component: "PayCash", name: "PayCash", compe: null },
  { slug: "paypal", component: "PayPal", name: "PayPal", compe: null },
  { slug: "picpay", component: "PicPay", name: "PicPay", compe: "380" },
  { slug: "pinbank", component: "PinBank", name: "PinBank", compe: null },
  { slug: "pine", component: "Pine", name: "Banco Pine", compe: "643" },
  { slug: "pluggy", component: "Pluggy", name: "Pluggy", compe: null },
  { slug: "qitech", component: "QITech", name: "QI Tech", compe: "329" },
  { slug: "qualitybank", component: "QualityDigitalBank", name: "Quality Digital Bank", compe: null },
  { slug: "rabobank", component: "Rabobank", name: "Banco Rabobank", compe: "747" },
  { slug: "recargapay", component: "RecargaPay", name: "RecargaPay", compe: null },
  { slug: "rendimento", component: "Rendimento", name: "Banco Rendimento", compe: "633" },
  { slug: "revolut", component: "Revolut", name: "Revolut", compe: null },
  { slug: "rico", component: "Rico", name: "Rico", compe: null },
  { slug: "safra", component: "Safra", name: "Banco Safra", compe: "422" },
  { slug: "santander", component: "Santander", name: "Santander", compe: "033" },
  { slug: "sicoob", component: "Sicoob", name: "Sicoob", compe: "756" },
  { slug: "sicredi", component: "Sicredi", name: "Sicredi", compe: "748" },
  { slug: "sisprime", component: "Sisprime", name: "Sisprime do Brasil", compe: "084" },
  { slug: "skrill", component: "Skrill", name: "Skrill", compe: null },
  { slug: "socgen", component: "SocieteGenerale", name: "Banco Société Générale Brasil", compe: "366" },
  { slug: "sofisa", component: "Sofisa", name: "Banco Sofisa", compe: "637" },
  { slug: "squid", component: "Squid", name: "Squid", compe: null },
  { slug: "starkbank", component: "StarkBank", name: "Stark Bank", compe: null },
  { slug: "stellantis", component: "BancoStellantis", name: "Banco Stellantis", compe: null },
  { slug: "stone", component: "Stone", name: "Stone", compe: "197" },
  { slug: "stripe", component: "Stripe", name: "Stripe", compe: null },
  { slug: "sulcredi", component: "Sulcredi", name: "Sulcredi", compe: null },
  { slug: "sumitomo", component: "SumitomoMitsui", name: "Banco Sumitomo Mitsui Brasileiro", compe: "464" },
  { slug: "ton", component: "Ton", name: "Ton", compe: null },
  { slug: "topazio", component: "Topazio", name: "Banco Topázio", compe: "082" },
  { slug: "toro", component: "Toro", name: "Toro Investimentos", compe: "352" },
  { slug: "toyota", component: "BancoToyota", name: "Banco Toyota", compe: "387" },
  { slug: "transfeera", component: "Transfeera", name: "Transfeera", compe: null },
  { slug: "tribanco", component: "Tribanco", name: "Tribanco", compe: "634" },
  { slug: "unicred", component: "Unicred", name: "Unicred", compe: "136" },
  { slug: "uniprime", component: "Uniprime", name: "Uniprime", compe: "099" },
  { slug: "uzzipay", component: "UzziPay", name: "UzziPay", compe: null },
  { slug: "volkswagen", component: "BancoVolkswagen", name: "Banco Volkswagen", compe: "393" },
  { slug: "warren", component: "Warren", name: "Warren Investimentos", compe: "371" },
  { slug: "willbank", component: "WillBank", name: "Will Bank", compe: null },
  { slug: "wise", component: "Wise", name: "Wise", compe: null },
  { slug: "xp", component: "XP", name: "XP", compe: "348" },
  { slug: "zemobank", component: "ZemoBank", name: "Zemo Bank", compe: null },
  { slug: "zrobank", component: "ZroBank", name: "Zro Bank", compe: null },
];
